server:
  port: 8031
  
spring:
  application:
    name: stock-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:8271/myeureka/eureka
  instance:
    prefer-ip-address: true

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"